TribalWebsite.Web/Areas/Admin/Controllers/AwardsController.cs
using System.Web;
using System.Web.Mvc;
using TribalWebsite.Api.Dto;
using TribalWebsite.Api.Interactions.AwardInteractions;

namespace TribalWebsite.Web.Areas.Admin.Controllers
{
    public class AwardsController : Controller
    {
        private IAwardInteraction awardInteraction;

        public AwardsController(IAwardInteraction awardInteraction)
        {
            this.awardInteraction = awardInteraction;
        }

        [Authorize]
        public ActionResult Index()
        {
            return View(awardInteraction.GetAllAwards());
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(AwardDto awardDto, HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0)
                awardInteraction.SaveAward(awardDto, file);

            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return RedirectToAction("Index");

            var model = awardInteraction.GetAwardById(id.Value);
            return View(model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit(AwardDto awardDto, HttpPostedFileBase file)
        {
            awardInteraction.UpdateAward(awardDto, file);
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult Delete(long? id)
        {
            if (id == null)
                return RedirectToAction("Index");

            var model = awardInteraction.GetAwardById(id.Value);
            return View(model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Delete(AwardDto awardDto)
        {
            awardInteraction.DeleteAward(awardDto);
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        public ActionResult SetOrder(long? id, int order)
        {
            awardInteraction.SetOrder(id, order);
            return RedirectToAction("Index");
        }


    }
}

TribalWebsite.Web/Areas/Admin/Views/Awards/Create.cshtml
@model TribalWebsite.Api.Dto.AwardDto


<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Yeni Ödül</h3>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        @using (Html.BeginForm("Create", "Awards", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            <div class="form-group">
                                <label>Ödül İsmi</label>
                                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                            </div>

                            <div class="form-group">
                                <label>Ödül Logosu Seçiniz</label>
                                <input type="file" id="file" name="file">
                            </div>

                            <input type="submit" class="btn btn-primary" value="Ekle" />
                            <a href="/Admin/Awards" class="btn btn-default">Vazgeç</a>

                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

TribalWebsite.Web/Areas/Admin/Views/Awards/Delete.cshtml
@model TribalWebsite.Api.Dto.AwardDto

<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Ödül Silme</h3>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        @using (Html.BeginForm("Delete", "Awards", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {

                            @Html.HiddenFor(model => model.Id)
                            @Html.HiddenFor(model => model.Name)
                            @Html.HiddenFor(model => model.MediaId)
                            @Html.HiddenFor(model => model.Order)
                            @Html.HiddenFor(model => model.State)
                            @Html.HiddenFor(model => model.LanguageId)

                            <div class="form-group">
                                <label>Ödül İsmi : </label>
                                @Model.Name
                            </div>

                            <div class="form-group">
                                <label>Ödül Logosu : </label>
                                <img src="@Model.Media.FilePath" height="100" />
                            </div>

                            <div class="alert alert-danger">
                                Dikkat! bu ödüle bağlı görseller, ödül detayları da silinecektir.<br />Ödülü silmek istediğinize emin misiniz?.
                            </div>

                            <input type="submit" class="btn btn-primary" value="Sil" />
                            <a href="/Admin/Award" class="btn btn-default">Vazgeç</a>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

TribalWebsite.Web/Areas/Admin/Views/Awards/Edit.cshtml
@model TribalWebsite.Api.Dto.AwardDto

<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Ödül Düzenleme</h3>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        @using (Html.BeginForm("Edit", "Awards", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.HiddenFor(model => model.Id)
                            @Html.HiddenFor(model => model.MediaId)
                            @Html.HiddenFor(model => model.Order)
                            @Html.HiddenFor(model => model.State)
                            @Html.HiddenFor(model => model.LanguageId)
                            @Html.HiddenFor(model => model.CreatedAt)

                            <div class="form-group">
                                <label>Ödül İsmi</label>
                                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                            </div>

                            <div class="form-group">
                                <label>Ödül Logosu</label>
                                <img src="@Model.Media.FilePath" height="100" />
                            </div>

                            <div class="form-group">
                                <label>Yeni Ödül Logosu Seçiniz</label>
                                <input type="file" id="file" name="file">
                            </div>

                            <input type="submit" class="btn btn-primary" value="Değiştir" />
                            <a href="/Admin/Awards" class="btn btn-default">Vazgeç</a>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

TribalWebsite.Web/Areas/Admin/Views/Awards/Index.cshtml
@model List<TribalWebsite.Api.Dto.AwardDto>

<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Ödüller</h3>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-6">
        <a href="/Admin/Awards/Create">+ Yeni Ödül Ekle</a>
        <div class="panel panel-default">
            <div class="panel-heading">
                Tüm Ödüller
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <table class="table table-striped table-bordered table-hover" id="dataTables-exampleAward">
                    <thead>
                        <tr>
                            <th>Görsel</th>
                            <th>Ödül</th>
                            <th>Sıra</th>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var award in Model)
                        {
                            <tr>
                                <td><img src="@award.Media.FilePath" height="100"/></td>
                                <td>@award.Name</td>
                                <td>
                                    @using (Html.BeginForm("SetOrder", "Awards", FormMethod.Post))
                                    {
                                        <div class="form-group">
                                            <input type="hidden" name="id" value="@award.Id" />
                                            <input style="width:40px" type="text" class="form-control" name="order" value="@award.Order" />
                                            <input type="submit" class="btn btn-primary" value="Değiştir" />
                                        </div>
                                    }
                                </td>
                                <td><a href="/Admin/AwardDetail/Index/@award.Id"><i class="fa fa-film fa-fw"></i> Detaylar</a></td>
                                <td><a href="/Admin/Awards/Edit/@award.Id"><i class="fa fa-edit fa-fw"></i> Düzenle</a></td>
                                <td><a href="/Admin/Awards/Delete/@award.Id"><i class="fa fa-times fa-fw"></i> Sil</a></td>
                            </tr>
                        }
                    </tbody>
                </table>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<script>
    $(document).ready(function() {
        $('#dataTables-exampleAward').DataTable({
            responsive: true
        });
    });
</script>