TribalWebsite.Web/Areas/Admin/Controllers/ClientController.cs
using System.Web;
using System.Web.Mvc;
using TribalWebsite.Api.Dto;
using TribalWebsite.Api.Interactions.ClientInteractions;

namespace TribalWebsite.Web.Areas.Admin.Controllers
{
    public class ClientController : Controller
    {
        private IClientInteraction clientInteraction;

        public ClientController(IClientInteraction clientInteraction)
        {
            this.clientInteraction = clientInteraction;
        }

        [Authorize]
        public ActionResult Index()
        {
            var model = clientInteraction.GetAllClients();

            return View(model);
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(ClientDto clientDto, HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0)
                clientInteraction.SaveClient(clientDto, file);

            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult Edit(long? id)
        {
            if (id == null)
                return RedirectToAction("Index");

            var model = clientInteraction.GetClientById(id.Value);
            return View(model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit(ClientDto clientDto, HttpPostedFileBase file)
        {
            clientInteraction.UpdateClient(clientDto, file);
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult State(long? id)
        {
            clientInteraction.SetState(id);
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        public ActionResult SetOrder(long? id, int order)
        {
            clientInteraction.SetOrder(id, order);
            return RedirectToAction("Index");
        }
    }
}

TribalWebsite.Web/Areas/Admin/Views/Client/Create.cshtml
@model TribalWebsite.Api.Dto.ClientDto

<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Yeni Müşteri</h3>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        @using (Html.BeginForm("Create", "Client", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            <div class="form-group">
                                <label>Müşteri İsmi</label>
                                @Html.TextBoxFor(model => model.Name, new { @class = "form-control", placeholder = "Müşterinin ismini giriniz (İş Bankası, Polat Holding vs.)" })
                            </div>

                            <div class="form-group">
                                <label>Müşteri Logosu Seçiniz</label>
                                <input type="file" id="file" name="file">
                            </div>

                            <input type="submit" class="btn btn-primary" value="Ekle" />
                            <a href="/Admin/Client" class="btn btn-default">Vazgeç</a>

                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

TribalWebsite.Web/Areas/Admin/Views/Client/Edit.cshtml
@model TribalWebsite.Api.Dto.ClientDto

<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Müşteri Düzenleme</h3>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        @using (Html.BeginForm("Edit", "Client", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.HiddenFor(model => model.Id)
                            @Html.HiddenFor(model => model.MediaId)
                            @Html.HiddenFor(model => model.Order)
                            @Html.HiddenFor(model => model.State)
                            @Html.HiddenFor(model => model.LanguageId)
                            @Html.HiddenFor(model => model.CreatedAt)

                            <div class="form-group">
                                <label>Müşteri İsmi</label>
                                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                            </div>

                            <div class="form-group">
                                <label>Müşteri Logosu</label>
                                <img src="@Model.Media.FilePath" height="100" />
                            </div>

                            <div class="form-group">
                                <label>Yeni Müşteri Logosu Seçiniz</label>
                                <input type="file" id="file" name="file">
                            </div>

                            <input type="submit" class="btn btn-primary" value="Değiştir" />
                            <a href="/Admin/Client" class="btn btn-default">Vazgeç</a>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

TribalWebsite.Web/Areas/Admin/Views/Client/Index.cshtml
@using Infrastructure.Data.Enums;
@model List<TribalWebsite.Api.Dto.ClientDto>

<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Müşteri</h3>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-6">
        <a href="/Admin/Client/Create">+ Yeni Müşteri Ekle</a>
        <div class="panel panel-default">
            <div class="panel-heading">
                Tüm Müşteriler
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <table class="table table-striped table-bordered table-hover" id="dataTables-exampleClient">
                    <thead>
                        <tr>
                            <th>Logo</th>
                            <th>Müşteri</th>
                            <th>Sıra</th>
                            <th></th>
                            <th>Durum</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var client in Model)
                        {
                            <tr>
                                <td><img src="@client.Media.FilePath" height="100" /></td>
                                <td>@client.Name</td>
                                <td>
                                    @using (Html.BeginForm("SetOrder", "Client", FormMethod.Post))
                                    {
                                        <div class="form-group">
                                            <input type="hidden" name="id" value="@client.Id" />
                                            <input style="width:40px" type="text" class="form-control" name="order" value="@client.Order" />
                                            <input type="submit" class="btn btn-primary" value="Değiştir" />
                                        </div>
                                    }
                                </td>
                                <td><a href="/Admin/Client/Edit/@client.Id"><i class="fa fa-edit fa-fw"></i> Düzenle</a></td>
                                <td>
                                    <a href="/Admin/Client/State/@client.Id">
                                        @if (client.State == (int)State.Active)
                                        {
                                            <i class="fa fa-check fa-fw"></i> <span>Aktif</span>
                                        }
                                        else
                                        {
                                            <i class="fa fa-close"></i> <span>Pasif</span>
                                        }
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<script>
    $(document).ready(function () {
        $('#dataTables-exampleClient').DataTable({
            responsive: true
        });
    });
</script>