TribalWebsite.Web/Areas/Admin/Controllers/CategoryController.cs
using System.Web.Mvc;
using TribalWebsite.Api.Dto;
using TribalWebsite.Api.Interactions.CategoryInteractions;

namespace TribalWebsite.Web.Areas.Admin.Controllers
{
    public class CategoryController : Controller
    {
        private ICategoryInteraction categoryInteraction;

        public CategoryController(ICategoryInteraction categoryInteraction)
        {
            this.categoryInteraction = categoryInteraction;
        }

        [Authorize]
        public ActionResult Index()
        {
            return View(categoryInteraction.GetAllCategories());
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(CategoryDto categoryDto)
        {
            categoryInteraction.SaveCategory(categoryDto);

            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult Edit(long? id)
        {
            if (id == null)
                return RedirectToAction("Index");

            var model = categoryInteraction.GetCategoryById(id.Value);
            return View(model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit(CategoryDto categoryDto)
        {
            categoryInteraction.UpdateCategory(categoryDto);
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        public ActionResult SetOrder(long? id, int order)
        {
            categoryInteraction.SetOrder(id, order);
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult State(long? id)
        {
            categoryInteraction.SetState(id);
            return RedirectToAction("Index");
        }
    }
}

TribalWebsite.Web/Areas/Admin/Views/Category/Create.cshtml
@model TribalWebsite.Api.Dto.CategoryDto

<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Yeni Kategori</h3>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        @using (Html.BeginForm("Create", "Category", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            <div class="form-group">
                                <label>Kategori İsmi</label>
                                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                            </div>

                            <input type="submit" class="btn btn-primary" value="Ekle" />
                            <a href="/Admin/Category" class="btn btn-default">Vazgeç</a>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

TribalWebsite.Web/Areas/Admin/Views/Category/Edit.cshtml
@model TribalWebsite.Api.Dto.CategoryDto

<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Kategori Düzenleme</h3>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        @using (Html.BeginForm("Edit", "Category", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.HiddenFor(model => model.Id)
                            @Html.HiddenFor(model => model.Order)
                            @Html.HiddenFor(model => model.State)
                            @Html.HiddenFor(model => model.LanguageId)
                            @Html.HiddenFor(model => model.CreatedAt)

                            <div class="form-group">
                                <label>Kategori İsmi</label>
                                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                            </div>

                            <input type="submit" class="btn btn-primary" value="Değiştir" />
                            <a href="/Admin/Category" class="btn btn-default">Vazgeç</a>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

TribalWebsite.Web/Areas/Admin/Views/Category/Index.cshtml
@using Infrastructure.Data.Enums;
@model List<TribalWebsite.Api.Dto.CategoryDto>

<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Kategoriler</h3>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-6">
        <a href="/Admin/Category/Create">+ Yeni Kategori Ekle</a>
        <div class="panel panel-default">
            <div class="panel-heading">
                Tüm Kategoriler
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <table class="table table-striped table-bordered table-hover" id="dataTables-exampleCategory">
                    <thead>
                        <tr>
                            <th>Adı</th>
                            <th>Sıra</th>
                            <th></th>
                            <th>Durum</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var category in Model)
                        {
                            <tr>
                                <td>@category.Name</td>
                                <td>
                                    @using (Html.BeginForm("SetOrder", "Category", FormMethod.Post))
                                    {
                                        <div class="form-group">
                                            <input type="hidden" name="id" value="@category.Id" />
                                            <input style="width:40px" type="text" class="form-control" name="order" value="@category.Order" />
                                            <input type="submit" class="btn btn-primary" value="Değiştir" />
                                        </div>
                                    }
                                </td>
                                <td><a href="/Admin/Category/Edit/@category.Id"><i class="fa fa-edit fa-fw"></i> Düzenle</a></td>
                                <td>
                                    <a href="/Admin/Category/State/@category.Id">
                                        @if (category.State == (int)State.Active)
                                        {
                                            <i class="fa fa-check fa-fw"></i> <span>Aktif</span>
                                        }
                                        else
                                        {
                                            <i class="fa fa-close"></i> <span>Pasif</span>
                                        }
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<script>
    $(document).ready(function () {
        $('#dataTables-exampleCategory').DataTable({
            responsive: true
        });
    });
</script>