TribalWebsite.Web/Areas/Admin/Controllers/AgencyController.cs
using System.Web;
using System.Web.Mvc;
using TribalWebsite.Api.Dto;
using TribalWebsite.Api.Interactions.AgencyInteractions;

namespace TribalWebsite.Web.Areas.Admin.Controllers
{
    public class AgencyController : Controller
    {
        private IAgencyInteraction agencyInteraction;

        public AgencyController(IAgencyInteraction agencyInteraction)
        {
            this.agencyInteraction = agencyInteraction;
        }

        [Authorize]
        public ActionResult Index()
        {
            var model = agencyInteraction.GetAgency();

            return View(model);
        }

        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return RedirectToAction("Index");

            var model = agencyInteraction.GetAgencyById(id.Value);
            return View(model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit(AgencyDto agencyDto, HttpPostedFileBase file)
        {
            agencyInteraction.UpdateAgency(agencyDto, file);
            return RedirectToAction("Index");
        }
    }
}

TribalWebsite.Web/Controllers/AgencyController.cs
using System.Web.Mvc;
using TribalWebsite.Api.PageInteractions.AgencyInteractions;

namespace TribalWebsite.Web.Controllers
{
    public class AgencyController : Controller
    {
        private IAgencyInteraction agencyInteraction;

        public AgencyController(IAgencyInteraction agencyInteraction)
        {
            this.agencyInteraction = agencyInteraction;
        }

        [Route("agency")]
        public ActionResult Index()
        {
            return View(agencyInteraction.GetAgencyPage());
        }
    }
}

TribalWebsite.Web/Areas/Admin/Views/Agency/Edit.cshtml
@model TribalWebsite.Api.Dto.AgencyDto

<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Ajans Düzenleme</h3>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        @using (Html.BeginForm("Edit", "Agency", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.HiddenFor(model => model.Id)
                            @Html.HiddenFor(model => model.MediaId)
                            @Html.HiddenFor(model => model.Order)
                            @Html.HiddenFor(model => model.State)
                            @Html.HiddenFor(model => model.LanguageId)
                            @Html.HiddenFor(model => model.CreatedAt)

                            <div class="form-group">
                                <label>Resim</label>
                                <img src="@Model.Media.FilePath" height="100" />
                            </div>


                            <div class="form-group">
                                <label>Yeni Resim Ekle</label>
                                <input type="file" id="file" name="file">
                            </div>


                            <div class="form-group">
                                <label>Başlık</label>
                                @Html.TextAreaFor(model => model.Content, new { @class = "form-control", rows = 20, cols = 20 })
                            </div>

                            <div class="form-group">
                                <label>Tarihçe</label>
                                @Html.TextAreaFor(model => model.History, new { @class = "form-control", rows = 20, cols = 20 })
                            </div>

                            <div class="form-group">
                                <label>Idea</label>
                                @Html.TextAreaFor(model => model.Idea, new { @class = "form-control", rows = 20, cols = 20 })
                            </div>

                            <input type="submit" class="btn btn-primary" value="Değiştir" />
                            <a href="/Admin/Agency" class="btn btn-default">Vazgeç</a>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

TribalWebsite.Web/Areas/Admin/Views/Agency/Index.cshtml
@model TribalWebsite.Api.Dto.AgencyDto

<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Ajans</h3>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Ajans Bilgileri
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <table class="table table-striped table-bordered table-hover" id="dataTables-exampleAgency">
                    <thead>
                        <tr>
                            <th>Resim</th>
                            <th>Başlık</th>
                            <th>Tarihçe</th>
                            <th>Idea</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><img src="@Model.Media.FilePath" height="100" /></td>
                            <td>@Model.Content</td>
                            <td>@Model.History</td>
                            <td>@Model.Idea</td>
                            <td><a href="/Admin/Agency/Edit/@Model.Id"><i class="fa fa-edit fa-fw"></i> Düzenle</a></td>
                        </tr>
                    </tbody>
                </table>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<script>
    $(document).ready(function () {
        $('#dataTables-exampleAgency').DataTable({
            responsive: true
        });
    });
</script>